added syntax validation

diff --git a/cloudbuild-test.yaml b/cloudbuild-test.yaml
--- a/cloudbuild-test.yaml
+++ b/cloudbuild-test.yaml
@@ -52,13 +52,15 @@ steps:
     args:
       - '-c'
       - |
-        apk add --no-cache gettext
+        apk add --no-cache gettext yq
         mkdir -p /workspace/tmp
         for file in k8s/test/*.yaml; do
           envsubst < "$file" > "/workspace/tmp/$(basename "$file")"
-          cat "/workspace/tmp/$(basename "$file")"
+          if ! yq eval -o=json "/workspace/tmp/$(basename "$file")" > /dev/null; then
+            echo "Error: Invalid YAML in /workspace/tmp/$(basename "$file")"
+            exit 1
+          fi
         done
-        ls -l /workspace/tmp
   - name: 'gcr.io/cloud-builders/kubectl'
     args: ['apply', '-f', '/workspace/tmp/db-migration-job.yaml', '--namespace=test']
     env:
